"""
backtest_v1.py -- Backtest v1 (mdabbert) models from the v1 feature CSV.

Loads ml/ufc_ml_data_v1.csv (generated by ml/ML_data_preparation_v1.py),
scores with models_v1/ artifacts, and reports accuracy year-by-year.

Usage:
    python scripts/backtest_v1.py
    python scripts/backtest_v1.py --from-year 2025
    python scripts/backtest_v1.py --model ensemble
"""

import argparse
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from config import (
    CSV_V1_WITH_ELO,
    DB_V1_PATH,
    META_COLS,
    MODEL_V1_ENSEMBLE_PATH,
    MODEL_V1_LGBM_FEATURES,
    MODEL_V1_LGBM_PATH,
    MODEL_V1_LR_FEATURES,
    MODEL_V1_LR_PATH,
    MODEL_V1_LR_SCALER,
    MODEL_V1_RF_FEATURES,
    MODEL_V1_RF_PATH,
    MODEL_V1_XGB_FEATURES,
    MODEL_V1_XGB_PATH,
    MODELS_V1_DIR,
    TARGET_COL,
)
from utils.logger import get_logger

log = get_logger(__name__)


def _load_csv() -> pd.DataFrame:
    if not CSV_V1_WITH_ELO.exists():
        log.error(
            "v1 feature CSV not found at '%s'. "
            "Run: python ml/ML_data_preparation_v1.py",
            CSV_V1_WITH_ELO,
        )
        sys.exit(1)
    df = pd.read_csv(CSV_V1_WITH_ELO)
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").reset_index(drop=True)
    log.info("Loaded %d rows from %s", len(df), CSV_V1_WITH_ELO.name)
    return df


def _score(df: pd.DataFrame, model_type: str) -> pd.DataFrame:
    specs = {
        "xgb":  (MODEL_V1_XGB_PATH,  MODEL_V1_XGB_FEATURES,  None,               False),
        "lr":   (MODEL_V1_LR_PATH,   MODEL_V1_LR_FEATURES,   MODEL_V1_LR_SCALER, True),
        "rf":   (MODEL_V1_RF_PATH,   MODEL_V1_RF_FEATURES,   None,               False),
        "lgbm": (MODEL_V1_LGBM_PATH, MODEL_V1_LGBM_FEATURES, None,               False),
    }

    if model_type == "ensemble":
        return _score_ensemble(df)

    m_path, f_path, s_path, is_lr = specs[model_type]
    artifact  = joblib.load(m_path)
    feat_names = joblib.load(f_path)
    scaler    = joblib.load(s_path) if s_path and s_path.exists() else None

    X = df.reindex(columns=feat_names, fill_value=0).fillna(0)
    Xi = scaler.transform(X) if scaler else X.values
    base = artifact["base"] if is_lr else artifact
    prob_red = base.predict_proba(Xi)[:, 1]
    return _make_results(df, prob_red)


def _score_ensemble(df: pd.DataFrame) -> pd.DataFrame:
    ens         = joblib.load(MODEL_V1_ENSEMBLE_PATH)
    weights     = ens.get("weights", {})
    calibrators = ens.get("calibrators", {})

    specs = [
        ("xgb",  MODEL_V1_XGB_PATH,  MODEL_V1_XGB_FEATURES,  None,               False),
        ("lr",   MODEL_V1_LR_PATH,   MODEL_V1_LR_FEATURES,   MODEL_V1_LR_SCALER, True),
        ("rf",   MODEL_V1_RF_PATH,   MODEL_V1_RF_FEATURES,   None,               False),
        ("lgbm", MODEL_V1_LGBM_PATH, MODEL_V1_LGBM_FEATURES, None,               False),
    ]

    model_probas   = []
    active_weights = []

    for m_key, m_path, f_path, s_path, is_lr in specs:
        if not m_path.exists() or not f_path.exists():
            continue
        artifact  = joblib.load(m_path)
        feat_names = joblib.load(f_path)
        scaler    = joblib.load(s_path) if s_path and s_path.exists() else None

        X  = df.reindex(columns=feat_names, fill_value=0).fillna(0)
        Xi = scaler.transform(X) if scaler else X.values
        base = artifact["base"] if is_lr else artifact
        raw_p = base.predict_proba(Xi)[:, 1]

        cal_p = calibrators[m_key].predict(raw_p) if m_key in calibrators else raw_p

        model_probas.append(cal_p)
        active_weights.append(weights.get(m_key, 1.0))

    total_w = sum(active_weights)
    active_weights = [w / total_w for w in active_weights]
    prob_red = np.average(model_probas, axis=0, weights=active_weights)
    return _make_results(df, prob_red)


def _make_results(df: pd.DataFrame, prob_red: np.ndarray) -> pd.DataFrame:
    predicted = (prob_red >= 0.5).astype(int)
    return pd.DataFrame({
        "date":      df["date"].values,
        "year":      df["date"].dt.year.values,
        "target":    df[TARGET_COL].values,
        "predicted": predicted,
        "correct":   (df[TARGET_COL].values == predicted).astype(int),
        "prob_red":  prob_red,
    })


def _print_report(results: pd.DataFrame, label: str, from_year: int | None) -> None:
    subset = results[results["year"] >= from_year] if from_year else results
    if subset.empty:
        print(f"  No fights found from {from_year}+.")
        return

    print(f"\n  {label}  |  from_year={from_year or 'all'}")
    print("-" * 40)

    for yr, grp in subset.groupby("year"):
        acc = grp["correct"].mean()
        n   = len(grp)
        print(f"  {yr}  {n:>6} fights  {acc:.1%}")

    acc_total = subset["correct"].mean()
    n_total   = len(subset)
    print(f"\n  Total  {n_total:>6} fights  {acc_total:.1%}")
    print()


def main() -> None:
    parser = argparse.ArgumentParser(description="Backtest v1 (mdabbert) models.")
    parser.add_argument("--from-year", type=int, default=None)
    parser.add_argument("--model", choices=["xgb", "lr", "rf", "lgbm", "ensemble"],
                        default="ensemble")
    args = parser.parse_args()

    if not MODELS_V1_DIR.exists():
        print(f"[ERROR] v1 models not found at '{MODELS_V1_DIR}'.")
        sys.exit(1)

    df      = _load_csv()
    results = _score(df, args.model)
    _print_report(results, f"v1 {args.model}", args.from_year)


if __name__ == "__main__":
    main()
